version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5012:5012"
    environment:
      MONGO_URI: mongodb://mongo:27017/to-do-list-db
